name: docker-build

on:
  push:
    branches: main
  pull_request:
    branches: main

env:
  DOCKER_ORGANIZATION: ${{ secrets.DOCKER_ORGANIZATION }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-php:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Deprecated: php-5.6, php-7.0, php-7.1, php-7.2 have been removed due to EOL
        tag: ["php-7.3",  "php-7.4", "php-8.0", "php-8.1", "php-8.1", "php-8.2", "php-8.3"]
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        env:
          TAG: ${{ matrix.tag }}
        run: |
          set -eux
          docker build -f ./Dockerfile-$TAG -t $DOCKER_ORGANIZATION/base-ws:$TAG .
          docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
          docker push $DOCKER_ORGANIZATION/base-ws:$TAG
  build-other:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag: [  "general" ]
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        env:
          TAG: ${{ matrix.tag }}
        run: |
          set -eux
          docker build -f ./Dockerfile-$TAG -t $DOCKER_ORGANIZATION/base-ws:$TAG .
          docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
          docker push $DOCKER_ORGANIZATION/base-ws:$TAG
